##===- lib/Bitcode/NaCl/Analysis/Makefile ------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../../..
LIBRARYNAME = LLVMNaClBitAnalysis
BUILD_ARCHIVE = 1

include $(LEVEL)/Makefile.common
