#===- tools/pnacl-llc/Makefile -----------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME := pnacl-llc
LINK_COMPONENTS := nacltransforms all-targets bitreader naclbitreader irreader \
                   asmparser naclanalysis naclbittestutils nacltransforms

include $(LEVEL)/Makefile.common
