#===- tools/llc/Makefile -----------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME := llc
LINK_COMPONENTS := nacltransforms all-targets bitreader asmparser irreader mirparser nacltransforms

# Support plugins.
NO_DEAD_STRIP := 1

include $(LEVEL)/Makefile.common

