#===- tools/pnacl-abicheck/Makefile ------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME := pnacl-abicheck
LINK_COMPONENTS := bitreader asmparser naclbitreader irreader naclanalysis

include $(LEVEL)/Makefile.common


