##===- lib/Bitcode/NaCl/Makefile ---------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
PARALLEL_DIRS = Writer

include $(LEVEL)/Makefile.common

